### PR TITLE
Add new Nginx versions

### PR DESCRIPTION
**Pull request by theboolean**
New versions:
- 1.8.1
- 1.9.6
- 1.9.7
- 1.9.8
- 1.9.9
- 1.9.10
- 1.9.11
- 1.9.12
- 1.9.13
- 1.9.14
- 1.9.15

### CODE REVIEW

**Comment by fntlnz** [comment]
Thanks for this!

**Comment by fntlnz** [comment]
@theboolean versions > 1.9.12 does not exist at all!

**Comment by theboolean** [comment]
@fntlnz OMG sorry! I made a mistake reporting the versions from the changelog.

**Comment by fntlnz** [comment]
No problem shitz happenz  :hankey: 

Thank you anyway

**Pull request merged**
